### ISSUE TITLE
Missing or odd site names

### ISSUE THREAD

**Issue by laura-vanvliet** [crim-ca/decision-support-tool#26]
If a user clicks through the module without providing a site name, or if they provide a name like "my great building" then the tool shows:
"... aspect of your ." or "... aspect of your _my great building_." or "... aspect of your _Laura's house_."
Some ideas to fix this, but won't be perfect in all cases:
- Have a default site name if none is given: "... aspect of your _building_."
- Remove certain words from before site names: "my"  "a" "an" "the" etc ("... aspect of your _great building_")

**Comment by JeremyFyke** [comment]
Closed and moved to General Bugs
