### ISSUE TITLE
Increased permissions?

### ISSUE THREAD

**Issue by JeremyFyke** [crim-ca/decision-support-tool#8]
Hi @matprov - could I get increased permissions on this repo, in order to be able to provide other ECCC-side developers basic write permissions?  There are a few folks coming in to help with the project, and I'd like them to be able to set up and work on their own sandbox branches.  If this is a problem and you want to maintain a sole admin role here, just let me know, in which case I will forward you names to add.  Thanks!

**Comment by matprov** [comment]
Hi @JeremyFyke , please send me the list of users and I'll add them.

**Comment by JeremyFyke** [comment]
@silvieharder

I think Ryan Smith (@ryan1000000) is already added?

**Comment by JeremyFyke** [comment]
PS - I hope it's OK I'm making use of Issues board on this repository.  I made 3 labels to (hopefully) keep issues separate.  You're welcome to ignore any issue labelled 'DST core', unless you want to dig into the actual DST development!  These issues are issues for tool development itself.

**Comment by matprov** [comment]
@JeremyFyke That's alright, labels are cheap ;) 
I've added silvieharder and ryan1000000 to the team, let me know if they haven't gain access to the DST repo. Thanks
